controller_list:
 - name: /dual_arm_pa10/left_arm/joint_trajectory_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - left_arm_joint2
      - left_arm_joint3
      - left_arm_joint4
      - left_arm_joint5
      - left_arm_joint6
      - left_arm_joint7
      - left_arm_joint8
   constraints:
    left_arm_joint7:
      goal: 0.5
    left_arm_joint2:
      goal: 0.5
    left_arm_joint3:
      goal: 0.5
    left_arm_joint4:
      goal: 0.5
    left_arm_joint5:
      goal: 0.5
    left_arm_joint6:
      goal: 0.5
    left_arm_joint8:
      goal: 0.5
 - name: /dual_arm_pa10/right_arm/joint_trajectory_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - right_arm_joint2
      - right_arm_joint3
      - right_arm_joint4
      - right_arm_joint5
      - right_arm_joint6
      - right_arm_joint7
      - right_arm_joint8
   constraints:
    right_arm_joint7:
      goal: 0.5
    right_arm_joint2:
      goal: 0.5
    right_arm_joint3:
      goal: 0.5
    right_arm_joint4:
      goal: 0.5
    right_arm_joint5:
      goal: 0.5
    right_arm_joint6:
      goal: 0.5
    right_arm_joint8:
      goal: 0.5
 - name: /dual_arm_pa10/right_arm/joint_trajectory_controller_hand
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - right_arm_finger1_joint1
      - right_arm_finger1_joint2
      - right_arm_finger1_joint3
      - right_arm_finger2_joint1
      - right_arm_finger2_joint2
      - right_arm_finger2_joint3
      - right_arm_finger3_joint1
      - right_arm_finger3_joint2
      - right_arm_finger3_joint3
   constraints:
    right_arm_finger1_joint1:
      goal: 0.5
    right_arm_finger1_joint2:
      goal: 0.5
    right_arm_finger1_joint3:
      goal: 0.5
    right_arm_finger2_joint1:
      goal: 0.5
    right_arm_finger2_joint2:
      goal: 0.5
    right_arm_finger2_joint3:
      goal: 0.5
    right_arm_finger3_joint1:
      goal: 0.5    
    right_arm_finger3_joint2:
      goal: 0.5
    right_arm_finger3_joint3:
      goal: 0.5
      
      