# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  gripper_left_joint_left:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_left_joint_right:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  left_arm_joint2:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  left_arm_joint3:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  left_arm_joint4:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  left_arm_joint5:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  left_arm_joint6:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  left_arm_joint7:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  left_arm_joint8:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_finger1_joint1:
    has_velocity_limits: true
    max_velocity: 1.37
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_finger1_joint2:
    has_velocity_limits: true
    max_velocity: 1.37
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_finger1_joint3:
    has_velocity_limits: true
    max_velocity: 1.37
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_finger2_joint1:
    has_velocity_limits: true
    max_velocity: 1.37
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_finger2_joint2:
    has_velocity_limits: true
    max_velocity: 1.37
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_finger2_joint3:
    has_velocity_limits: true
    max_velocity: 1.37
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_finger3_joint1:
    has_velocity_limits: true
    max_velocity: 1.37
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_finger3_joint2:
    has_velocity_limits: true
    max_velocity: 1.37
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_finger3_joint3:
    has_velocity_limits: true
    max_velocity: 1.37
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_joint2:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_joint3:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_joint4:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_joint5:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_joint6:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_joint7:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_joint8:
    has_velocity_limits: true
    max_velocity: 10
    has_acceleration_limits: false
    max_acceleration: 0