/dual_arm_pa10/right_arm:
   # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000
    default : true
  joint_trajectory_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - right_arm_joint2
      - right_arm_joint3
      - right_arm_joint4
      - right_arm_joint5
      - right_arm_joint6
      - right_arm_joint7
      - right_arm_joint8
    gains:
      right_arm_joint2: {p: 400.0,i: 0.95, d: 15.0}
      right_arm_joint3: {p: 2800.0,i: 0.95, d: 18.0}
      right_arm_joint4: {p: 450.0,i: 1.75, d: 10.0}
      right_arm_joint5: {p: 1100.0,i: 1.75, d: 12.0}
      right_arm_joint6: {p: 150.0,i: 5.5, d: 5.0}
      right_arm_joint7: {p: 120.0,i: 5.5, d: 8.0}
      right_arm_joint8: {p: 100.0,i: 0.1, d: 0.01}